# Generated by Django 6.0.3 on 2026-04-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_resumeuploadrecord_parsed_json'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='resumeuploadrecord',
            new_name='resume_uplo_status_dcf10d_idx',
            old_name='resume_uplo_status_137061_idx',
        ),
        migrations.RenameIndex(
            model_name='resumeuploadrecord',
            new_name='resume_uplo_created_bd3050_idx',
            old_name='resume_uplo_created_685891_idx',
        ),
    ]
